"""GNU ld linker script generation."""

from __future__ import annotations


def generate_linker_script(
    stubs_archive_name: str,
    prefixed_so_name: str,
) -> str:
    """Generate a GNU ld script that ties stubs to the real .so.

    The script is installed as the unversioned linker name (e.g. libzstd.so).
    When a consumer links with -lzstd, the linker reads this script, pulls
    symbols from the stubs archive, and links against the real .so via
    AS_NEEDED.

    Args:
        stubs_archive_name: Filename of the stubs archive (e.g. "librocm_zstd_stubs.a").
        prefixed_so_name: Filename of the prefixed .so (e.g. "librocm_sysdeps_zstd.so.1").

    Returns:
        The linker script text.
    """
    return (
        f"/* GNU ld script — generated by isolib, do not edit */\n"
        f"INPUT({stubs_archive_name} AS_NEEDED({prefixed_so_name}))\n"
    )
