"""ASM trampoline generation for symbol redirection."""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

from isolib.model import SymbolRename, SymbolType


def generate_trampoline_asm(renames: list[SymbolRename], arch: str) -> str:
    """Generate assembly source for trampoline stubs.

    Each stub exports the original unprefixed name and does a tail-jump
    to the prefixed name via PLT.

    Only FUNC and IFUNC symbols get trampolines. OBJECT and TLS symbols
    are skipped (cannot be trampolined).

    Args:
        renames: Symbol renames to generate trampolines for.
        arch: Target architecture ("x86_64" or "aarch64").

    Returns:
        Assembly source as a string.
    """
    func_renames = [
        r
        for r in renames
        if r.sym_type in (SymbolType.FUNC, SymbolType.IFUNC)
    ]

    if not func_renames:
        return ""

    lines: list[str] = [
        "/* Generated by isolib — do not edit */",
        f"/* {len(func_renames)} trampoline stubs for {arch} */",
        "",
    ]

    for r in func_renames:
        if arch == "x86_64":
            lines.extend(_x86_64_stub(r))
        elif arch == "aarch64":
            lines.extend(_aarch64_stub(r))
        else:
            raise ValueError(f"Unsupported architecture: {arch}")
        lines.append("")

    return "\n".join(lines) + "\n"


def _x86_64_stub(r: SymbolRename) -> list[str]:
    return [
        f".section .text.{r.original},\"ax\",@progbits",
        f".globl {r.original}",
        f".type {r.original}, @function",
        f"{r.original}:",
        f"    jmp {r.prefixed}@PLT",
        f".size {r.original}, .-{r.original}",
    ]


def _aarch64_stub(r: SymbolRename) -> list[str]:
    return [
        f".section .text.{r.original},\"ax\",@progbits",
        f".globl {r.original}",
        f".type {r.original}, @function",
        f"{r.original}:",
        f"    b {r.prefixed}",
        f".size {r.original}, .-{r.original}",
    ]


def build_stubs_archive(
    asm_source: str,
    output_archive: Path,
    arch: str,
    assembler: Path = Path("as"),
    archiver: Path = Path("ar"),
    renames: list[SymbolRename] | None = None,
) -> None:
    """Assemble trampoline stubs and package them into a static archive.

    Each stub gets its own .o file so the linker only pulls archive
    members that satisfy unresolved references. Without this, linking
    against the archive pulls ALL stubs (e.g. 400 zstd trampolines)
    even if the consumer only uses 10 functions.

    Args:
        asm_source: Assembly source text (used as fallback if renames not provided).
        output_archive: Path for the output .a file.
        arch: Target architecture.
        assembler: Path to the assembler.
        archiver: Path to the archiver (ar).
        renames: If provided, generates per-symbol .o files for fine-grained linking.

    Raises:
        RuntimeError: If assembly or archiving fails, or output is empty.
    """
    if not asm_source.strip():
        raise ValueError("Empty assembly source")

    func_renames = [
        r for r in (renames or [])
        if r.sym_type in (SymbolType.FUNC, SymbolType.IFUNC)
    ]

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)
        obj_files: list[Path] = []

        if func_renames:
            # Per-symbol .o files for fine-grained archive linking
            for r in func_renames:
                if arch == "x86_64":
                    stub_lines = _x86_64_stub(r)
                elif arch == "aarch64":
                    stub_lines = _aarch64_stub(r)
                else:
                    raise ValueError(f"Unsupported architecture: {arch}")

                asm_file = tmp / f"{r.original}.s"
                obj_file = tmp / f"{r.original}.o"
                asm_file.write_text("\n".join(stub_lines) + "\n")

                subprocess.run(
                    [str(assembler), "-o", str(obj_file), str(asm_file)],
                    check=True, capture_output=True, text=True,
                )
                if obj_file.exists() and obj_file.stat().st_size > 0:
                    obj_files.append(obj_file)
        else:
            # Fallback: single .o from full asm source
            asm_file = tmp / "stubs.s"
            obj_file = tmp / "stubs.o"
            asm_file.write_text(asm_source)

            subprocess.run(
                [str(assembler), "-o", str(obj_file), str(asm_file)],
                check=True, capture_output=True, text=True,
            )
            if not obj_file.exists() or obj_file.stat().st_size == 0:
                raise RuntimeError("Assembler produced no output")
            obj_files.append(obj_file)

        # Archive all .o files
        subprocess.run(
            [str(archiver), "rcs", str(output_archive)] + [str(o) for o in obj_files],
            check=True, capture_output=True, text=True,
        )

    if not output_archive.exists() or output_archive.stat().st_size == 0:
        raise RuntimeError(f"Archiver produced no output: {output_archive}")
