"""Redirect header generation for compile-time symbol redirection."""

from __future__ import annotations

from isolate_elf.model import SymbolRename


def generate_redirect_header(
    renames: list[SymbolRename],
    guard_macro: str,
) -> str:
    """Generate a C header with #define redirects for all renamed symbols.

    Consumers that include this header before the library's own header
    get compile-time redirection to prefixed names, bypassing trampolines.

    Args:
        renames: All symbol renames (FUNC, OBJECT, etc.).
        guard_macro: Include guard name (e.g. "ROCM_ISOLIB_ZSTD_REDIRECT_H").

    Returns:
        The header text.
    """
    lines = [
        f"#ifndef {guard_macro}",
        f"#define {guard_macro}",
        "/* Generated by isolate-elf — compile-time symbol redirection */",
        "",
    ]

    for r in sorted(renames, key=lambda r: r.original):
        lines.append(f"#define {r.original} {r.prefixed}")

    lines.extend(["", f"#endif /* {guard_macro} */", ""])
    return "\n".join(lines)
